interface AiInterpretationSectionProps {
  interpretation: string | null;
}

export function AiInterpretationSection({ interpretation }: AiInterpretationSectionProps) {
  return (
    <section className="bg-white border border-slate-200 shadow-sm rounded-2xl p-8">
      <h2 className="text-xl font-bold text-slate-900 mb-1">Your Personalized Analysis</h2>
      <p className="text-slate-500 text-sm mb-6">
        Generated by our AI based on your unique performance pattern
      </p>
      {interpretation ? (
        <p className="text-slate-700 leading-relaxed text-base">{interpretation}</p>
      ) : (
        <p className="text-slate-400 italic text-sm">
          Your personalized interpretation is being generated. Refresh in a few moments.
        </p>
      )}
    </section>
  );
}
